#!/usr/bin/env bash

thePid=$(ps auxww|grep java|grep quickstart|awk '{print $2}')

if [[ -n $thePid ]]
then
    kill -9 $thePid
fi

while kill -0 $thePid
do
    sleep 1
done 2>/dev/null

#rm -rf /tmp/blobs

#export initJournal=56c15a45-bdbc-9afa-f0b3-1d707b8a15ef

YJP_ARGS="-Dorg.apache.sling.launcher.bootdelegation=com.yourkit.api,com.yourkit.runtime,com.yourkit.util -Xbootclasspath/a:/Users/ahanikel/Downloads/YourKit-Java-Profiler-2016.02.app/Contents/Resources/lib/yjp-controller-api-redist.jar -agentpath:/Users/ahanikel/Downloads/YourKit-Java-Profiler-2016.02.app/Contents/Resources/bin/mac/libyjpagent.jnilib"

DEBUG='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'

export clusterInstances=1
export writeBackJournal=true
export writeBackNodes=true
export remoteReads=true
export customBlobStore=false
export backendPrefix=localhost
export logNodeStates=false
export blobCacheDir=/tmp/blobCacheDir
export ZEROMQ_LEADER=true

rm -rf ~/Downloads/crx-quickstart
#cp -pR ~/Downloads/crx-quickstart.test-1.44.0 ~/Downloads/crx-quickstart
rm -rf /tmp/blobCacheDir

#(cd /Users/ahanikel/Downloads && java -Xmx16g $DEBUG -Doak.queryLimitReads=10000000 -Dorg.apache.sling.launchpad.startupmode=restart -jar cq-quickstart-6.6.0-1.44.0.nosegment.jar -nofork -nobrowser -r author,crx3,crx3tar-nofds) &
(cd /Users/ahanikel/Downloads && java -Xmx16g $DEBUG -Dorg.apache.sling.launchpad.startupmode=update -jar cq-quickstart-6.6.0-1.44.0.nosegment.jar -nofork -nobrowser -r author,crx3raw) &

