#!/usr/bin/env bash

#thePid=$(ps auxww|grep java|grep quickstart|awk '{print $2}')
#
#if [[ -n $thePid ]]
#then
#    kill -9 $thePid
#fi
#
#while kill -0 $thePid
#do
#    sleep 1
#done 2>/dev/null

#rm -rf /tmp/blobs

#export initJournal=56c15a45-bdbc-9afa-f0b3-1d707b8a15ef

YJP_ARGS="-Dorg.apache.sling.launcher.bootdelegation=com.yourkit.api,com.yourkit.runtime,com.yourkit.util -Xbootclasspath/a:/Users/ahanikel/Downloads/YourKit-Java-Profiler-2016.02.app/Contents/Resources/lib/yjp-controller-api-redist.jar -agentpath:/Users/ahanikel/Downloads/YourKit-Java-Profiler-2016.02.app/Contents/Resources/bin/mac/libyjpagent.jnilib"

DEBUG='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007'

export clusterInstances=1
export writeBackJournal=true
export writeBackNodes=true
export remoteReads=true
export customBlobStore=false
export backendPrefix=localhost
export logNodeStates=false
export blobCacheDir=/tmp/blobCacheDir-2
export ZEROMQ_LEADER=false

rm -rf ~/Downloads/inst-2
rm -rf /tmp/blobCacheDir-2
mkdir ~/Downloads/inst-2
#cp -pR ~/Downloads/crx-quickstart.test-1.44.0 ~/Downloads/inst-2/crx-quickstart
cp ~/Downloads/license.properties ~/Downloads/inst-2/

(cd /Users/ahanikel/Downloads/inst-2 && java -Xmx16g $DEBUG -Doak.queryLimitReads=10000000 -jar ../cq-quickstart-6.6.0-1.44.0.nosegment.jar -nofork -nobrowser -r author,crx3,crx3tar-nofds -p4505) &

