#!/usr/bin/env bash

thePid=$(ps auxww|grep java|grep quickstart|awk '{print $2}')

if [[ -n $thePid ]]
then
    kill $thePid
fi

while kill -0 $thePid
do
    sleep 1
done 2>/dev/null

rm -rf /tmp/blobs

(cd /Users/axel/Downloads && echo admin | java -Xmx8g '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005' -DclusterInstances=2 -Doak.queryLimitReads=10000000 -jar cq-quickstart-6.6.0-1.30.0.nosegment.jar -nofork -nobrowser -r crx3,crx3tar-nofds) &
