#!/usr/bin/env bash

YJP_ARGS="-Dorg.apache.sling.launcher.bootdelegation=com.yourkit.api,com.yourkit.runtime,com.yourkit.util -Xbootclasspath/a:/Users/axel/yjp/lib/yjp-controller-api-redist.jar -agentpath:/Users/axel/yjp/bin/linux-x86-64/libyjpagent.so"

export clusterInstances=1
export writeBackJournal=true
export writeBackNodes=true
export customBlobStore=false
export backendPrefix=localhost
export blobendPrefix=localhost
export journalPrefix=localhost
export initJournal=undefined
export logNodeStates=false

./killaem
cp oak-store-zeromq/target/oak-store-zeromq-1.30.0.jar /Users/axel/Downloads/install.zeromq/15/
(cd /Users/axel/Downloads &&
    rm -rf crx-quickstart && rm -rf /tmp/blobs && rm -rf /Users/axel/Downloads/blobs && (rm -f /tmp/zmqBlob* || true) && mkdir crx-quickstart && cp -R install.zeromq crx-quickstart/install)
(cd /Users/axel/Downloads && echo admin | java -Xmx8g '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005' -Doak.queryLimitReads=10000000 -jar cq-quickstart-6.6.0-1.37.0.nosegment.jar -nofork -nobrowser -r author,crx3,crx3tar-nofds & )
