#!/usr/bin/env bash

ps auxww|grep java|grep quickstart|awk '{print $2}'|xargs kill -9
#(cd /Users/axel/Documents/git/jackrabbit-oak/quickstart-remotesegment-docker && docker-compose down)
(cd /Users/axel/Downloads &&
    rm -rf crx-quickstart && rm -rf /tmp/blobs && rm -rf /Users/axel/Downloads/blobs && (rm -f /tmp/zmqBlob* || true) && mkdir crx-quickstart && cp -R install.zeromq crx-quickstart/install)
