version: "3"
services:
  backend0:
    image: docker2-granite-release-local.dr-uw2.adobeitc.com/ahanikel/oak-store-zeromq-service-store:1.38.0-zeromq
    ports:
            - "8000-8001:8000-8001"
            - "6006:6006"
    environment:
        - ZEROMQ_NTHREADS=12
        # these should not be necessary:
        - KAFKA_TOPIC=nodestates
        - KAFKA_SERVERS=kafka:9092
        - clusterInstances=1
        - writeBackJournal=true
        - customBlobStore=false
        - backendPrefix=localhost
        - blobendPrefix=localhost
        - journalPrefix=localhost
        - initJournal=undefined
        - logNodeStates=false

  quickstart:
    image: docker2-granite-release-local.dr-uw2.adobeitc.com/ahanikel/quickstart-remotesegment-docker:1.38.0-zeromq
    ports:
      - "4502:4502"
      - "5005:5005"
    environment:
      - backendPrefix=backend
      - javaargs=-Xmx16g -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005
      - jarargs=-nofork -nobrowser -r author,crx3,crx3tar-nofds
      - blobCacheDir=/tmp/blurbs
      # these should not be necessary:
      - clusterInstances=1
      - writeBackJournal=true
      - writeBackNodes=true
      - remoteReads=true
      - customBlobStore=false
      - logNodeStates=false
      - delay=180

