version: "3"
services:
  backend0:
    image: myhub/ahanikel/oak-store-zeromq-service-store
    ports:
      - "8000-8001"
  backend1:
    image: myhub/ahanikel/oak-store-zeromq-service-store
    ports:
      - "8000-8001"
  journal:
    image: myhub/ahanikel/oak-store-zeromq-service-journal
    ports:
      - "9000-9001"
  quickstart:
    image: myhub/ahanikel/quickstart-remotesegment-docker
    ports:
      - "4502:4502"
      - "5005:5005"
    environment:
      - clusterInstances=2
      - backendPrefix=backend
      - journalPrefix=journal
      - javaargs=-Xmx8g -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=*:5005
      - jarargs=-nofork -nobrowser
