#!/usr/bin/env bash
cd $(dirname $0)

export KAFKA_TOPIC=nodestates
export KAFKA_SERVERS=localhost:9092
export clusterInstances=1
export writeBackJournal=true
export customBlobStore=false
export backendPrefix=localhost
export blobendPrefix=localhost
export journalPrefix=localhost
export initJournal=undefined
export logNodeStates=false

debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=6006"
logging="-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd'T'HH:mm:ss.SSSZ"
jar=~/Documents/git/jackrabbit-oak/oak-store-zeromq-service-store/target/oak-store-zeromq-service-store-1.30.0-jar-with-dependencies.jar
jarOpts="log golden test-diff.log"
#jarOpts="server httpbackend.yaml"

ps auxww | grep java | grep oak-store-zeromq-service-store | awk '{print $2}' | xargs kill -9
sleep 5
#java -Xmx16g $debug $logging -jar $jar $jarOpts 2>&1 | tee /tmp/zeromq-service-error.log
java -Xmx16g -jar $jar $jarOpts
