#!/usr/bin/env bash
cd $(dirname $0)

export KAFKA_TOPIC=nodestates
export KAFKA_SERVERS=localhost:9092
export ZEROMQ_READER_URL='tcp://*:8000'
export ZEROMQ_WRITER_URL='tcp://*:8001'
export ZEROMQ_NTHREADS=4

debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=6006"
logging="-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd'T'HH:mm:ss.SSSZ"
jar=~/Documents/git/jackrabbit-oak/oak-store-zeromq-service-store/target/oak-store-zeromq-service-store-1.38.0-zeromq-jar-with-dependencies.jar
jarOpts="log test-diff-1.38.0.log"
#jarOpts="server httpbackend.yaml"

rm -rf /tmp/blobs

ps auxww | grep java | grep oak-store-zeromq-service-store | awk '{print $2}' | xargs kill -9
sleep 1
touch test-diff-1.38.0.log
java -Xmx16g $debug $logging -jar $jar $jarOpts
