#!/bin/bash -e

function usage {
    cat <<EOF >&2
Usage: $0 <instance> <instances>
where
    instance  = the number of this instance (counting starts with 1)
    instances = the total number of instances in the cluster
EOF
}

if [[ $# != 2 ]]
then
    usage
    exit 1
fi

instance=$1
instances=$2
debugPort=$((30302 + instance))
port=$((8079 + instance))
workDir="/tmp/clu$instance"
thisDir=$(cd $(dirname $0) && pwd)

if [[ $instance < 1 || $instance > $instances ]]
then
    usage
    exit 2
fi

rm -rf "$workDir"
mkdir "$workDir"

(
    cd "$workDir"
    java -DclusterInstance=$instance -DclusterInstances=$instances -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=$debugPort -jar $thisDir/target/oak-store-zeromq-service-store-*.jar -p $port
)

