#!/bin/bash -e

debugPort=30403
port=8090
workDir="/tmp/journal"
thisDir=$(cd $(dirname $0) && pwd)

rm -rf "$workDir"
mkdir "$workDir"

(
    cd "$workDir"
    java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=$debugPort -jar $thisDir/target/oak-segment-journal-standalone-*.jar -p $port
)

